/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


//PD12 - Green_LED _GLOW

#include <stdint.h>

uint32_t *RCC_AHB1ENR = (uint32_t *)0x40023830; //clock Address
uint32_t *GPIOD_MODER = (uint32_t *)0x40020C00; //MODER Address
uint32_t *GPIOD_ODR = (uint32_t *)0x40020C14; // Output Address

int main(void)
{
    *RCC_AHB1ENR |= (1 << 3);
    *GPIOD_MODER &= ~( 1 << 25);
    *GPIOD_MODER |= ( 1 << 24);
    while(1){
    	*GPIOD_ODR |= (1 << 12);
    }
}
