/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//PD13 //ORANGE LED
#include <stdint.h>

uint32_t *RCC_AHB1ENR = (uint32_t *) 0X40023830;
uint32_t *GPIOE_MODER = (uint32_t *) 0X40021000;
uint32_t *GPIOE_ODR = (uint32_t *) 0X40021014;

int main(void)
{
    *RCC_AHB1ENR |= (1 << 4);
    *GPIOE_MODER |= (1 << 22);
    *GPIOE_MODER &= ~(1 << 23);


    while(1){

    	*GPIOE_ODR |= (1 << 11);
    	for(int i=0; i<400000; i++);
    	*GPIOE_ODR &= ~(1 << 11);
    	for(int i=0; i<400000; i++);

    }
}
